<!doctype html>
<html class="signin no-js" lang="">


<head>
    <!-- meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">
    <!-- /meta -->

    <title>Test Medialab Mario</title>

    <!-- page level plugin styles -->
    <!-- /page level plugin styles -->

    <!-- core styles -->
    <link rel="stylesheet" href="<?php echo $this->basePath()?>/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo $this->basePath()?>/css/font-awesome.css">
    <link rel="stylesheet" href="<?php echo $this->basePath()?>/css/themify-icons.css">
    <link rel="stylesheet" href="<?php echo $this->basePath()?>/css/animate.min.css">
    <!-- /core styles -->

    <!-- template styles -->
    <link rel="stylesheet" href="<?php echo $this->basePath()?>/css/skins/palette.css">
    <link rel="stylesheet" href="<?php echo $this->basePath()?>/css/fonts/font.css">
    <link rel="stylesheet" href="<?php echo $this->basePath()?>/css/main.css">
    <!-- template styles -->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- load modernizer -->
    <script src="<?php echo $this->basePath()?>/plugins/modernizr.js"></script>
</head>

<body class="bg-primary">

    <div class="cover" style="background-image: url(<?php echo $this->basePath()?>/img/cover3.jpg)"></div>

    <div class="overlay bg-primary"></div>

    <div class="center-wrapper">
        <div class="center-content">
            <div class="row">
                <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
                    <section class="panel bg-white no-b">
                        <ul class="switcher-dash-action">
                            <li class="active"><a href="#" class="selected">Login</a></li>
                            <li><a href="<?php echo $this->basePath()?>/usuario/registro" class="">Registrarse</a></li>
                        </ul>
                        <div class="p15">  

							<?php echo $this->content; ?>


                        </div>
                    </section>
                    <p class="text-center">
                        Copyright &copy;
                        <span id="year" class="mr5"></span>
                        <span>Mario Carlomagno Concha Flores</span>
                    </p>
                </div>
            </div>
        
        </div>
    </div>

</body>



</html>

